name: Docker Build and Publish

on:
  push:
    branches:
      - main
  schedule:
    - cron: "33 3 26 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Fetch latest version
        id: fetch-version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/dushixiang/next-terminal/releases/latest | jq -r '.tag_name')
          CURRENT_VERSION=$(cat version)
          if [ "$LATEST_VERSION" = "$CURRENT_VERSION" ]; then
            echo "Versions match. Skipping build."
            echo "::set-output name=skip_build::true"
          else
            echo "::set-output name=latest_version::$LATEST_VERSION"
          fi

      - name: Build and push Docker image (latest)
        if: steps.fetch-version.outputs.skip_build != 'true'
        run: |
          docker build -t aaronlee/next-terminal:latest .
          docker push aaronlee/next-terminal:latest

      - name: Build and push Docker image (versioned)
        if: steps.fetch-version.outputs.skip_build != 'true'
        run: |
          LATEST_VERSION=${{ steps.fetch-version.outputs.latest_version }}
          docker build -t aaronlee/next-terminal:${{ steps.fetch-version.outputs.latest_version }} .
          docker push aaronlee/next-terminal:${{ steps.fetch-version.outputs.latest_version }}

      - name: Build and push Docker image (versioned with timestamp)
        if: steps.fetch-version.outputs.skip_build != 'true'
        run: |
          LATEST_VERSION=${{ steps.fetch-version.outputs.latest_version }}
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          docker build -t aaronlee/next-terminal:${{ steps.fetch-version.outputs.latest_version }}-${TIMESTAMP} .
          docker push aaronlee/next-terminal:${{ steps.fetch-version.outputs.latest_version }}-${TIMESTAMP}

      - name: Update version file and push to GitHub
        if: steps.fetch-version.outputs.skip_build != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_VERSION=${{ steps.fetch-version.outputs.latest_version }}
          echo $LATEST_VERSION > version
          git config user.email "your-email@example.com"
          git config user.name "Your Name"
          git add version
          git commit -m "Update version to $LATEST_VERSION"
          git push origin main
