name: Docker Build and Publish

on:
  push:
    branches:
      - main
  schedule:
    - cron: "13 3 24 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Fetch latest version
        id: fetch-version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/dushixiang/next-terminal/releases/latest | jq -r '.tag_name')
          CURRENT_VERSION=$(cat version)
          if [ "$LATEST_VERSION" = "$CURRENT_VERSION" ]; then
            echo "Versions match. Skipping build."
            echo "::set-output name=skip_build::true"
          else
            echo "::set-output name=latest_version::$LATEST_VERSION"
          fi

      - name: Build and push Docker image (latest)
        if: steps.fetch-version.outputs.skip_build != 'true'
        run: |
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t aaronlee/next-terminal:latest --push .

      - name: Build and push Docker image (versioned)
        if: steps.fetch-version.outputs.skip_build != 'true'
        run: |
          LATEST_VERSION=${{ steps.fetch-version.outputs.latest_version }}
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t aaronlee/next-terminal:${{ steps.fetch-version.outputs.latest_version }} --push .

      - name: Build and push Docker image (versioned with timestamp)
        if: steps.fetch-version.outputs.skip_build != 'true'
        run: |
          LATEST_VERSION=${{ steps.fetch-version.outputs.latest_version }}
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t aaronlee/next-terminal:${{ steps.fetch-version.outputs.latest_version }}-${TIMESTAMP} --push .

      - name: Update version file and push to GitHub
        if: steps.fetch-version.outputs.skip_build != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_VERSION=${{ steps.fetch-version.outputs.latest_version }}
          echo $LATEST_VERSION > version
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add version
          git commit -m "Update version to $LATEST_VERSION"
          git push origin main

      - name: 写入时间到文件
        run: echo $(date +"%Y-%m-%d %H:%M:%S") > time

      - name: 提交和推送时间更改
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add time
          git commit -m "更新时间文件"
          git push
